"use client";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
export function ExpenseForms({ categories, materials }: { categories: { id: string; name: string }[]; materials: { id: string; name: string }[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>, endpoint: string) {
    e.preventDefault(); setBusy(true); setMessage(""); const form = e.currentTarget; const data: Record<string, string | number> = Object.fromEntries(new FormData(form).entries()) as Record<string, string>;
    for (const key of ["amount", "quantity"]) if (key in data) data[key] = Number(data[key]);
    if ("date" in data) data.date = new Date(String(data.date)).toISOString();
    try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر الحفظ"); form.reset(); router.refresh(); setMessage("تم الحفظ"); } catch (error) { setMessage(error instanceof Error ? error.message : "حدث خطأ"); } finally { setBusy(false); }
  }
  return <div className="grid gap-4 lg:grid-cols-2"><form className="space-y-3 rounded-xl border bg-white p-4 lg:col-span-2" onSubmit={e => submit(e, "/api/expenses/categories")}><h2 className="font-semibold">إضافة فئة مصروفات</h2><input required name="name" maxLength={100} placeholder="اسم الفئة" className="rounded border p-2" /> <button type="submit" disabled={busy} className="rounded bg-blue-700 px-4 py-2 text-white">إضافة الفئة</button></form><form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={e => submit(e, "/api/expenses")}><h2 className="font-semibold">مصروف جديد</h2><select required name="categoryId" className="w-full rounded border p-2" defaultValue=""><option value="" disabled>الفئة</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input required name="amount" type="number" min="0.01" step="0.01" placeholder="المبلغ" className="w-full rounded border p-2" /><input required name="date" type="date" className="w-full rounded border p-2" /><input name="description" maxLength={500} placeholder="الوصف" className="w-full rounded border p-2" /><button type="submit" disabled={busy} className="rounded bg-blue-700 px-4 py-2 text-white">حفظ المصروف</button></form><form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={e => submit(e, "/api/purchases")}><h2 className="font-semibold">شراء مادة وإضافتها للمخزون</h2><select required name="materialId" defaultValue="" className="w-full rounded border p-2"><option value="" disabled>المادة</option>{materials.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input required name="quantity" type="number" min="0.000001" step="any" placeholder="الكمية" className="w-full rounded border p-2" /><input required name="amount" type="number" min="0.01" step="0.01" placeholder="التكلفة" className="w-full rounded border p-2" /><input required name="date" type="date" className="w-full rounded border p-2" /><input name="reference" placeholder="رقم فاتورة اختياري" className="w-full rounded border p-2" /><button type="submit" disabled={busy} className="rounded bg-blue-700 px-4 py-2 text-white">حفظ الشراء</button></form>{message && <p role="status">{message}</p>}</div>;
}
