import Link from "next/link";
import { requireAuth } from "@/lib/auth-helpers";
import { can } from "@/lib/rbac";
import { getBusinessReport } from "@/services/report.service";
import { RangeFilter } from "@/components/reports/RangeFilter";
import { SalesBars } from "@/components/reports/SalesBars";
type Params = { period?: string; from?: string; to?: string };
export default async function DashboardPage({ searchParams }: { searchParams: Promise<Params> }) {
  const session = await requireAuth(); if (!can(session.role, "dashboard.read")) throw new Error("Forbidden");
  const query = await searchParams;
  const report = await getBusinessReport(session.storeId, { period: query.period, from: query.from, to: query.to });
  const currency = report.currency;
  const cards = [["إجمالي المبيعات", report.sales.gross, true], ["صافي المبيعات", report.sales.net, true], ["الطلبات", report.sales.orders, false], ["الوحدات المباعة", report.sales.units, false], ["المرتجعات", report.returns.count, false], ["تكلفة المرتجعات", report.returns.costs, true], ["المصروفات (تشمل المرتجعات)", report.expenses.total, true]] as const;
  return <main className="space-y-6 p-4 md:p-8"><header><h1 className="text-2xl font-bold">لوحة التحكم</h1><p className="text-sm text-gray-600">الأداء المالي للمتجر · {report.range.from} إلى {report.range.to} ({report.range.timeZone})</p></header><RangeFilter base="/dashboard" period={report.range.period} from={query.from} to={query.to} />{report.notes.excludedDifferentCurrencyOrders > 0 && <p className="rounded bg-amber-50 p-3 text-sm">تم استبعاد {report.notes.excludedDifferentCurrencyOrders} طلب بعملة مختلفة عن {currency} من المبيعات.</p>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, isMoney]) => <div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-gray-500">{label}</p><strong className="mt-2 block text-2xl tabular-nums">{isMoney ? `${Number(value).toFixed(2)} ${currency}` : value}</strong></div>)}</section><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-semibold">صافي المبيعات يوميًا</h2><SalesBars days={report.salesByDay} currency={currency} /></section><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-semibold">أفضل المنتجات حسب صافي مبيعات الطلبات</h2>{report.products.slice(0, 6).map(p => <div key={p.key} className="flex justify-between gap-2 border-t py-2 text-sm"><span>{p.product} · {p.variant}</span><span>{p.net.toFixed(2)} {currency}</span></div>)}{!report.products.length && <p className="text-sm text-gray-500">لا توجد بيانات.</p>}</section></div><section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">تنبيهات المخزون</h2><div className="flex flex-wrap gap-2">{report.lowStock.map(item => <span key={item.id} className="rounded bg-amber-50 px-3 py-1 text-sm text-amber-900">{item.name}: {item.stock} {item.unit} (الحد {item.reorderLevel})</span>)}{!report.lowStock.length && <span className="text-sm text-gray-500">لا توجد تنبيهات.</span>}</div></section><Link href="/dashboard/reports" className="inline-block text-blue-700 underline">كل التقارير ←</Link></main>;
}
